
  # project name does not matter, it is set by docker.projectNameFormat 
  # default is <Image Name> <Image Tag> <Image ID>
  # repositoryNameAndTag = <Image Name> <Image Tag>
  # repositoryName = <Image Name>

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'build'

- task: CmdLine@2
  inputs:
    script: |
      curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
      export WS_DOCKER_INCLUDES=".*$(Build.Repository.Name).*"
      export WS_DOCKER_LAYERS=true
      java -jar wss-unified-agent.jar -apikey $(APIKEY) -product "$(System.TeamProject)" -project "$(Build.Repository.Name)" -docker.scanImages true

