# replace .war with .jar or .ear if needed
name: Whitesource Prioritize Java with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn clean install -DskipTests=true
    - name: WhiteSource Unified Agent Scan
      env:
        WS_APIKEY: ${{secrets.APIKEY}}
      run: |
        curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
        echo UA downloaded successfully
        WARFILE=$(find ./ -type f -wholename "*/target/*.war")
        export WS_ENABLEIMPACTANALYSIS=true
        export WS_REQUIREKNOWNSHA1=false
        export WS_RESOLVEALLDEPENDENCIES=false
        export WS_MAVEN_RESOLVEDEPENDENCIES=true
        export WS_MAVEN_AGGREGATEMODULES=true
        java -jar wss-unified-agent.jar -appPath $WARFILE -d ./ -product GH_${{ github.event.repository.name }} -project ${{ github.ref }}_Prioritize