name: Whitesource Prioritize Java with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn clean install -DskipTests=true
    - name: WhiteSource Unified Agent Scan
      env:
        APIKEY: ${{secrets.APIKEY}}
      run: |
        cat <<EOF > eua.config
        apiKey=$APIKEY
        productName=GH_${{ github.event.repository.name }}
        projectName=${{ github.ref }}_Prioritize
        enableImpactAnalysis=true
        requireKnownSha1=false
        resolveAllDependencies=false
        maven.resolveDependencies=true
        maven.aggregateModules=true
        includes=**/*.*
        EOF
        less eua.config
        echo config created successfully
        curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
        curl -LJO https://unified-agent.s3.amazonaws.com/xModuleAnalyzer/xModuleAnalyzer-20.12.2.jar
        echo UA downloaded successfully
        java -jar wss-unified-agent.jar -d ./ -analyzeMultiModule multimodule.txt
        java -jar xModuleAnalyzer-20.12.2.jar -xModulePath multimodule.txt -fsaJarPath ./wss-unified-agent.jar -c ./eua.config -aggregateModules true -euaMode 1
