# add APIKEY as an environment variable - https://gitlab.com/help/ci/variables/README
image: maven:3.8-openjdk-8
build:
  stage: build
  only:
    - merge_requests
  script: |
    mvn clean install -DskipTests=true
    echo build completed successfully
    cat <<EOF > eua.config
    apiKey="$APIKEY"
    productName=GL_"$CI_PROJECT_DIR"
    projectName="$CI_COMMIT_BRANCH"_Prioritize
    enableImpactAnalysis=true
    requireKnownSha1=false
    resolveAllDependencies=false
    maven.resolveDependencies=true
    maven.aggregateModules=true
    includes=**/*c **/*cc **/*cp **/*cpp **/*cxx **/*c++ **/*h **/*hh **/*hpp **/*hxx **/*h++ **/*m **/*mm **/*pch **/*c# **/*cs **/*csharp **/*go **/*goc **/*js **/*pl **/*plx **/*pm **/*ph **/*cgi **/*fcgi **/*pod **/*psgi **/*al **/*perl **/*t **/*pl6 **/*p6m **/*p6l **/*pm6 **/*nqp **/*6pl **/*6pm **/*p6 **/*php **/*py **/*rb **/*swift **/*java **/*clj **/*cljx **/*cljs **/*cljc **/*jar **/*egg **/*dll **/*tar.gz **/*tgz **/*zip **/*whl **/*gem **/*apk **/*air **/*dmg **/*exe **/*gem **/*gzip **/*msi **/*nupkg **/*swc **/*swf **/tar.bz2 **/pkg.tar.xz **/(u)?deb **/(a)?rpm
    EOF
    cat eua.config
    echo config created successfully
    curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
    curl -o xModuleAnalyzer.jar https://unified-agent.s3.amazonaws.com/xModuleAnalyzer/xModuleAnalyzer-21.4.1.jar
    echo UA downloaded successfully
    java -jar wss-unified-agent.jar -d ./ -analyzeMultiModule multimodule.txt
    echo 'multimodule.txt contents'
    cat multimodule.txt
    java -jar xModuleAnalyzer.jar -xModulePath multimodule.txt -fsaJarPath ./wss-unified-agent.jar -c ./eua.config -aggregateModules true