# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  node: circleci/node@4.7.0
jobs:
  example-mend-sast-job:
    docker:
      # prebuilt image with java
      - image: cimg/openjdk:16.0.2
    steps:
      - checkout
      # execute Mend scan, curling the latest CLI. Remeber to set environmental variables (SAST Organization, SAST CLI Token, and SAST Server)
      - run: 
          name: Download Mend SAST CLI
          command: bash <(curl -LJO https://downloads-sast.whitesourcesoftware.com/sast-cli/linux/wssastcli && chmod +x wssastcli)
      - run: 
          name: Run Mend SAST
         # command: ls src/main
          command: ./wssastcli --dir ./ --app=circleci --baseline=true
          environment:
            SAST_ORGANIZATION: sast_organization_secret
            SASTCLI_TOKEN: sast_cli_secret
            SAST_SERVER: https://sast-demo.whitesourcesoftware.com
workflows:
  example-workflow:
    jobs:
      - example-mend-sast-job
