# add SAST_ORGANIZATION and SASTCLI_TOKEN as an environment variable - https://gitlab.com/help/ci/variables/README
default:
  image: ubuntu:latest

stages:
  - scan

ws_scan:
  stage: scan
  variables:
    SAST_ORGANIZATION: $SAST_ORGANIZATION
    SASTCLI_TOKEN: $SASTCLI_TOKEN
    SAST_SERVER: "https://sast-demo.whitesourcesoftware.com"
  script:
    - echo "Downloading WS SAST Tool"
    - curl -LJO https://downloads-sast.whitesourcesoftware.com/sast-cli/linux/wssastcli && chmod +x wssastcli
    - echo "Run WS SAST"
    - ./wssastcli --dir ./ --name=$CI_PROJECT_NAME_$CI_COMMIT_BRANCH --app=$CI_PROJECT_NAME
